usuario_valido: '0uxuPY0cbmQhpEz1'
usuario_inexistente: 'EsseIdNaoExiste'

usuario_admin:
  email: fulano@qa.com
  password: teste

usuario_nao_admin:
  email: usuarionaoadmin@teste.com.br
  password: naoadmin